In [3]:
# 01 - Coleta de Dados

In [42]:
# 1. Importação das Bibliotecas

import yfinance as yf
import pandas as pd
from pathlib import Path

In [11]:
# 2 Definição do Ativo e Período

ticker = "^BVSP"
data_inicio = "2010-01-01"
data_fim = "2026-01-01"

In [16]:
# 3. Download dos dados

df = yf.download(
    ticker,
    start=data_inicio,
    end=data_fim,
    auto_adjust=False
)

# Headers do dataset
df.head()

[*********************100%***********************]  1 of 1 completed

Price      Adj Close    Close     High      Low     Open   Volume
Ticker         ^BVSP    ^BVSP    ^BVSP    ^BVSP    ^BVSP    ^BVSP
Date
2010-01-04   70045.0  70045.0  70081.0  68587.0  68587.0  1655400
2010-01-05   70240.0  70240.0  70595.0  69928.0  70046.0  1984200
2010-01-06   70729.0  70729.0  70937.0  70016.0  70237.0  2243600
2010-01-07   70451.0  70451.0  70723.0  70045.0  70723.0  1555000
2010-01-08   70263.0  70263.0  70766.0  70158.0  70455.0  1634400

In [13]:
# Tamanho do dataset (linhas, colunas)

df.shape

(3965, 6)

In [17]:
# Informações das colunas

df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 3965 entries, 2010-01-04 to 2025-12-30
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   (Adj Close, ^BVSP)  3965 non-null   float64
 1   (Close, ^BVSP)      3965 non-null   float64
 2   (High, ^BVSP)       3965 non-null   float64
 3   (Low, ^BVSP)        3965 non-null   float64
 4   (Open, ^BVSP)       3965 non-null   float64
 5   (Volume, ^BVSP)     3965 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 216.8 KB

In [18]:
# Validação da data mais antiga e a mais recente do dataset

df.index.min(), df.index.max()

(Timestamp('2010-01-04 00:00:00'), Timestamp('2025-12-30 00:00:00'))

In [20]:
# validação se existem valores nulos em alguma coluna

df.isna().sum()

Price      Ticker
Adj Close  ^BVSP     0
Close      ^BVSP     0
High       ^BVSP     0
Low        ^BVSP     0
Open       ^BVSP     0
Volume     ^BVSP     0
dtype: int64

In [26]:
# Validação se existem duplicatas

df.index.duplicated().sum(),

df.duplicated().sum()

np.int64(0)

In [29]:
# Visão inicial de alguns stats do dataset

df.describe()

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,^BVSP,^BVSP,^BVSP,^BVSP,^BVSP,^BVSP
count,3965.000000,3965.000000,3965.000000,3965.000000,3965.000000,3.965000e+03
mean,84699.683228,84699.683228,85423.738966,83951.364691,84678.393947,6.102611e+06
std,30036.521534,30036.521534,30169.030428,29883.339168,30012.923675,4.083514e+06
min,37497.000000,37497.000000,38031.000000,37046.000000,37501.000000,0.000000e+00
25%,57550.000000,57550.000000,58114.000000,57068.000000,57561.000000,3.026100e+06
50%,74657.000000,74657.000000,75470.000000,74145.000000,74656.000000,4.360000e+06
75%,111996.000000,111996.000000,113057.000000,110935.000000,111995.000000,9.119300e+06
max,164456.000000,164456.000000,165036.000000,161759.000000,164461.000000,2.602930e+07

In [34]:
# Transformar retorno do yFinance em uma tabela

if isinstance(df.columns, pd.MultiIndex):
    df.columns = df.columns.get_level_values(0)

df = df.reset_index()

# Organizar a ordem das colunas
df = df[ [ "Date", "Open", "High", "Low", "Close", "Adj Close", "Volume" ] ]

# Ordenar os dados do dataset
df = df.sort_values("Date").reset_index(drop=True)

df.head()

Price       Date     Open     High      Low    Close  Adj Close   Volume
0     2010-01-04  68587.0  70081.0  68587.0  70045.0    70045.0  1655400
1     2010-01-05  70046.0  70595.0  69928.0  70240.0    70240.0  1984200
2     2010-01-06  70237.0  70937.0  70016.0  70729.0    70729.0  2243600
3     2010-01-07  70723.0  70723.0  70045.0  70451.0    70451.0  1555000
4     2010-01-08  70455.0  70766.0  70158.0  70263.0    70263.0  1634400

In [40]:
# Validação final dos dados

print("### Validação final ###\n")
print("Quantidade de linhas: ", len(df))
print("Data inicial: ", df["Date"].min())
print("Data final: ", df["Date"].max())
print("\nValores Ausentes:")
print(df.isna().sum())
print("\nDuplicatas: ", df.duplicated().sum())

### Validação final ###

Quantidade de linhas:  3965
Data inicial:  2010-01-04 00:00:00
Data final:  2025-12-30 00:00:00

Valores Ausentes:
Price
Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

Duplicatas:  0

In [52]:
# Criação do diretório de saída

raw_dir = Path("data/raw")
raw_dir.mkdir(parents=True, exist_ok=True)

if raw_dir.exists() and raw_dir.is_dir():
    print(f"SUCESSO: O diretório {raw_dir} foi criado ou já existia")
else: 
    print(f"ERRO: O diretório {raw_dir} não foi encontrado")

SUCESSO: O diretório data\raw foi criado ou já existia

In [53]:
# Criação do arquivo e save dos dados brutos

arquivo_saida = raw_dir / "ibovespa_raw.csv"

df.to_csv(arquivo_saida, index=False)

if arquivo_saida.exists():
    print(f"Arquivo salvo em {arquivo_saida}")
else: 
    print("O arquivo não foi criado")

arquivo_saida.exists()

Arquivo salvo em data\raw\ibovespa_raw.csv

True

In [54]:
print("Diretório atual:")
print(Path.cwd())

print("\nCaminho calculado:")
print(arquivo_saida)

print("\nCaminho absoluto:")
print(arquivo_saida.resolve())

Diretório atual:
C:\Users\markn\GitHub\LM_Projects\classificacao-volatibilidade-ibovespa

Caminho calculado:
data\raw\ibovespa_raw.csv

Caminho absoluto:
C:\Users\markn\GitHub\LM_Projects\classificacao-volatibilidade-ibovespa\data\raw\ibovespa_raw.csv